formatter: "pretty" # this is required

version: ">= 0.13.0, < 0.25.0"

header-from: main.tf
#footer-from: ""

recursive:
  enabled: false
  path: ./
  include-main: true

sections:
  show:
    - header
    - providers
    - data-sources
    - inputs
    - outputs



content: |-
  {{ .Header }}

  # k8s-s3-storage: multi-function bucket for object storage

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
